[workspace]
resolver = "3"
members = [
  # Core Components
  "src/main",
  "src/kernel",
  "src/api",

  # Modules
  "src/modules/identity",
]

[workspace.package]
edition = "2024"
rust-version = "1.96"
repository = "https://github.com/tacticasystems/tactica"
authors = ["Tactica Team"]

[workspace.dependencies]
async-trait = "0.1"
axum = { version = "0.8", features = ["macros"] }
anyhow = "1.0"
cel = { version = "0.14", features = ["structs", "chrono"] }
tokio = { version = "1.53", features = ["full"] }
clap = { version = "4.6", features = ["derive"] }
figment = { version = "0.10", features = ["env"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower = "0.5"
tower-http = { version = "0.7", features = ["request-id", "trace", "cors", "timeout", "limit"] }
url = { version = "2.5", features = ["serde"] }
http = "1.5"
newtype-uuid = { version = "1.4", features = ["serde", "v7"] }
newtype-uuid-macros = "0.1"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
uuid = { version = "1", features = ["serde"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "postgres", "chrono", "uuid", "json", "migrate", "macros"] }
derive_more = { version = "2.1", features = ["from"] }

# Core Components
tactica-api.path = "./src/api"
tactica-kernel.path = "./src/kernel"
tactica-module-identity.path = "./src/modules/identity"
