[workspace]
resolver = "3"
members = [
  "src/api",
  "src/main",
]

[workspace.package]
edition = "2024"
rust-version = "1.96"
repository = "https://github.com/tacticasystems/tactica"
authors = ["Tactica Team"]

[workspace.dependencies]
axum = { version = "0.8", features = ["macros"] }
tokio = { version = "1.53", features = ["full"] }
clap = { version = "4.6", features = ["derive"] }

# Core Components
tactica-api.path = "./src/api"
tactica-db.path = "./src/db"
