[package]
name = "tactica"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
serde.workspace = true
figment.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

tactica-api.workspace = true
tactica-db.workspace = true
tactica-module-identity.workspace = true
